[build]
builder = "nixpacks"
buildCommand = "npm install && npx turbo run build --filter=@moyo/frontend"

[deploy]
startCommand = "npx next start apps/frontend"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
